#!/bin/sh /etc/rc.common
START=70
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/daqemon /etc/daqemon/config.json
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/daqemon.pid
    procd_close_instance
}